# Generated by Django 2.1.7 on 2021-06-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder_product',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
