# Generated by Django 2.1.7 on 2021-06-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0002_bidder_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pyment_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=30)),
            ],
        ),
    ]
