# Generated by Django 2.1.7 on 2021-06-29 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0003_pyment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=50)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('total_amt', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amt_status', models.IntegerField(default=0)),
                ('order_status', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=30)),
                ('bid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidder.Bidder_product')),
            ],
        ),
    ]
