# Generated by Django 2.1.7 on 2021-06-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0005_auto_20210629_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder_product',
            name='place_status',
            field=models.IntegerField(default=0),
        ),
    ]
