# Generated by Django 2.1.7 on 2021-06-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_product_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
