# Generated by Django 2.1.7 on 2021-06-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20210608_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_img',
            field=models.ImageField(blank=True, upload_to='product_image'),
        ),
        migrations.AlterField(
            model_name='product_images',
            name='product_images',
            field=models.ImageField(blank=True, upload_to='product_image'),
        ),
    ]
