# Generated by Django 2.1.7 on 2021-06-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
