# Generated by Django 2.1.7 on 2021-06-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_auto_20210623_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
    ]
