# Generated by Django 2.1.7 on 2021-06-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0013_remove_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
