# Generated by Django 2.1.7 on 2021-06-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_product_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
    ]
